// Deprecated: import from "../schemas" instead. Types are re-exported for backward compatibility.

export {
  type Testament,
  type BookInfo,
  type Verse,
  type Chapter,
  type Book,
  type ParsedBible,
  type TranslationMeta,
  type LanguageInfo,
  type ParsedReference,
  type LanguagesResponse,
  type TranslationsResponse,
  type BooksResponse,
  type BookResponse,
  type ChaptersResponse,
  type ChapterResponse,
  type VerseResponse,
  type VersesRangeResponse,
  type MultipleVersesResponse,
  type CompareResponse,
  type SearchResult,
  type SearchResponse,
  type ErrorResponse,
} from "../schemas";
