// Re-export all schemas and types

// Core domain schemas
export {
  TestamentSchema,
  type Testament,
  BookInfoSchema,
  type BookInfo,
  VerseSchema,
  type Verse,
  ChapterSchema,
  type Chapter,
  BookSchema,
  type Book,
  ParsedBibleSchema,
  type ParsedBible,
  TranslationMetaSchema,
  type TranslationMeta,
  LanguageInfoSchema,
  type LanguageInfo,
  ParsedReferenceSchema,
  type ParsedReference,
  BookNamesSchema,
  type BookNames,
  BookDataSchema,
  type BookData,
} from "./bible";

// API response schemas
export {
  LanguagesResponseSchema,
  type LanguagesResponse,
  TranslationItemSchema,
  type TranslationItem,
  TranslationsResponseSchema,
  type TranslationsResponse,
  BookListItemSchema,
  type BookListItem,
  BooksResponseSchema,
  type BooksResponse,
  BookResponseSchema,
  type BookResponse,
  BookRefSchema,
  type BookRef,
  ChapterSummarySchema,
  type ChapterSummary,
  ChaptersResponseSchema,
  type ChaptersResponse,
  VerseTextSchema,
  type VerseText,
  ChapterResponseSchema,
  type ChapterResponse,
  VerseResponseSchema,
  type VerseResponse,
  VersesRangeResponseSchema,
  type VersesRangeResponse,
  MultipleVerseItemSchema,
  type MultipleVerseItem,
  MultipleVersesResponseSchema,
  type MultipleVersesResponse,
  ComparisonItemSchema,
  type ComparisonItem,
  CompareResponseSchema,
  type CompareResponse,
  SearchResultSchema,
  type SearchResult,
  SearchResponseSchema,
  type SearchResponse,
  ErrorResponseSchema,
  type ErrorResponse,
} from "./responses";

// Database row schemas
export {
  TranslationRowSchema,
  type TranslationRow,
  VerseRowSchema,
  type VerseRow,
  ChapterCountRowSchema,
  type ChapterCountRow,
  SearchRowSchema,
  type SearchRow,
} from "./database";

// Query parameter schemas
export {
  LanguageQuerySchema,
  type LanguageQuery,
  TranslationQuerySchema,
  type TranslationQuery,
  SearchQuerySchema,
  type SearchQuery,
  RefsQuerySchema,
  type RefsQuery,
  CompareQuerySchema,
  type CompareQuery,
} from "./query-params";
